Blanco cat
Gridnbird/javascript pull request #9
Opened 2020-05-15 12:31 UTC by Gridnbird

@smartianin check, please

2020-05-18 12:21 UTC, smartianin requested changes

2020-05-18 12:21 UTC, smartianin commented on IteratorsPracticePart_1.js
> +    console.log(number * number);
Можешь в написании программ постепенно отвыкать от console.log(). Он будет нужен тебе только для отладки

2020-05-18 12:21 UTC, smartianin commented on IteratorsPracticePart_1.js
> +    console.log(number * number);
Используй `Math`

2020-05-18 12:21 UTC, smartianin commented on IteratorsPracticePart_1.js
> +    console.log(number * number);
`console.log()` не используй, вместо него пиши `return`

2020-05-18 12:21 UTC, smartianin commented on IteratorsPracticePart_1.js
> +    return number * number;
`Math`

2020-05-18 12:21 UTC, smartianin commented on IteratorsPracticePart_1.js
> +console.log(numbers4.every(checkElements));
Инлайнить функции нужно, если они дублируются, или для упрощения понимания кода. Избавься от консоль логов везде

2020-05-21 20:10 UTC, smartianin approved these changes

2020-05-23 10:55 UTC, smartianin requested changes

2020-05-23 10:55 UTC, smartianin commented on IteratorsPracticePart_2.js
> +function even(number) {
не называй функции так, как потом сам не вспомнишь почему назвал)))

2020-05-23 10:55 UTC, smartianin commented on IteratorsPracticePart_2.js
> +function even(number) {
```suggestion
function isEven(number) {
```

2020-05-23 10:55 UTC, smartianin commented on IteratorsPracticePart_2.js
> +function block(numbers) {
```suggestion
function isArray(element) {
```

2020-05-25 15:57 UTC, smartianin requested changes

2020-05-25 15:57 UTC, smartianin commented on IteratorsPracticePart_3.js
> +let result1 = numbers12.reduce((x, y) => {
Во первых я не вижу чтобы ты эту переменную `result1` как-то использовал. Если не пользуешься, то зачем объявлять?

2020-05-25 15:57 UTC, smartianin commented on IteratorsPracticePart_3.js
> +    if (y == 0) {
Во-вторых используй `===` вместо `==`

2020-05-25 15:57 UTC, smartianin commented on IteratorsPracticePart_3.js
> +    }
И в третьих, поменяй значения массива на const `numbers12 = [1, 0, 3, 0, 4, 5, 6];` и посмотри что будет.

Вывод: не пиши программы в лоб. Думай о различных сценариях, при которых данные будут динамичными.

2020-05-25 15:57 UTC, smartianin commented on IteratorsPracticePart_3.js
> +});
Аналогичные ошибки

2020-05-25 17:58 UTC, Gridnbird commented on IteratorsPracticePart_3.js
> +    }
при втором попадании на 0 (если между ними есть другое число) пишет NaN, если два 0 стоят рядом то пишет undefined... я не совсем понимаю, как тут сделать динамичней😟думал, else if еще прописать? Или как?

2020-06-09 10:20 UTC, smartianin commented on IteratorsPracticePart_3.js
> +    }
Прямой ответ я тебе не дам ))) а кто ж тогда учиться будет. Чтобы выяснить в чем лажа, начинай дебажить свой код. Если умеешь пользоваться инструментами разработчика браузера –– вставляй break points, и смотри, что твой код выдает при каждой итерации. Если не умеешь, не страшно –– вставляй `console.log("Значение, которое нужно проверить", value)`, где value – это то самое значение.

2020-06-12 09:56 UTC, smartianin reviewed
Лови пример к 12 заданию. Разбирай и проводи свою работу над ошибками

2020-06-12 09:56 UTC, smartianin commented on IteratorsPracticePart_3.js
> +    }
Лови, пример
```
let numbers = [1, 4, 2, 0, 4, 5, 6];
let sumOfNumsBeforeTheZero = 0;
let isZeroMet = false;

numbers.reduce((sum, current) => {
  if (current === 0 && !isZeroMet) {
    isZeroMet = true;
    sumOfNumsBeforeTHeZero = sum;
  }
  
  return sum + current;
}, 0);

console.log(sumOfNumsBeforeTHeZero);
```

2020-06-17 14:59 UTC, smartianin requested changes
16 переделать

2020-06-30 11:41 UTC, smartianin approved these changes

2020-06-30 11:47 UTC, smartianin reviewed
Изучи код спджешшины и двигай дальше

2020-06-30 11:47 UTC, smartianin commented on IteratorsPracticePart_2.js
> +const evenNumbers = numbers7.filter(isEven);
```suggestion
const evenNumbers = numbers7.filter(number => number % 2 == 0);
```

2020-06-30 11:47 UTC, smartianin commented on IteratorsPracticePart_2.js
> +};
```suggestion
```

2020-06-30 11:47 UTC, smartianin commented on IteratorsPracticePart_2.js
> +const moreThanFive = stringsArray.filter(five);
```suggestion
const moreThanFive = stringsArray.filter(str => str.length > 5);
```

2020-06-30 11:47 UTC, smartianin commented on IteratorsPracticePart_2.js
> +}
```suggestion
```

2020-06-30 11:47 UTC, smartianin commented on IteratorsPracticePart_2.js
> +let underArray = numbersArray.filter(isArray);
```suggestion
let underArray = numbersArray.filter(number => Array.isArray(number));
```

2020-06-30 11:47 UTC, smartianin commented on IteratorsPracticePart_2.js
> +};
```suggestion
```

2020-06-30 11:47 UTC, smartianin commented on IteratorsPracticePart_2.js
> +});
```suggestion
let negativeNumbers = numbers10.filter(numbers => numbers < 0);
```

2020-06-30 11:47 UTC, smartianin commented on IteratorsPracticePart_2.js
> +});
```suggestion
let total = numbers11.reduce((firstvalue, value) => firstvalue + value);
```

2020-06-30 11:47 UTC, smartianin commented on IteratorsPracticePart_4.js
> +
```suggestion
```

2020-07-02 10:30 UTC, smartianin approved these changes

2020-07-14 14:39 UTC, merged